AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda: Download podcast episodes and save to S3

Parameters:
  BucketName:
    Type: String
    Default: podcast-download

Resources:
  PodcastDownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: podcast-download
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      Architectures: [arm64]
      Timeout: 600
      MemorySize: 512
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName
