AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Notify AWS cost to Discord channel

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Parameters:
  DiscordWebhookUrl:
    Type: String

Resources:
  AwsCostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: aws-cost
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      Architectures:
        - arm64
      Environment:
        Variables:
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ce:GetCostAndUsage'
              Resource: '*'

Outputs:
  AwsCostFunction:
    Description: AwsCost Function ARN
    Value: !GetAtt AwsCostFunction.Arn
