AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambdiko - IP simulcast radio download tools for AWS Lambda

Parameters:
  BucketName:
    Type: String
    Default: radiko-download
  LogGroupName:
    Type: String
    Default: /aws/lambda/lambdiko

Globals:
  Function:
    Runtime: ruby3.3
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON
      LogGroup: !Ref LogGroupName

Resources:
  RadikoDownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambdiko-radiko-download
      CodeUri: radiko-download/
      Handler: app.lambda_handler
      MemorySize: 512
      Timeout: 600
      Layers:
        - !Ref FFmpegLayer
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName

  RadiruDownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambdiko-radiru-download
      CodeUri: radiru-download/
      Handler: app.lambda_handler
      MemorySize: 512
      Timeout: 600
      Layers:
        - !Ref FFmpegLayer
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName

  ProgramSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambdiko-program-search
      CodeUri: program-search/
      Handler: app.lambda_handler
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          RADIKO_DL_FUNC_NAME: !GetAtt RadikoDownloadFunction.Arn
          RADIRU_DL_FUNC_NAME: !GetAtt RadiruDownloadFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref RadikoDownloadFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RadiruDownloadFunction

  FFmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: FFmpegLayer
      Description: FFmpeg binary
      ContentUri: layers/
      CompatibleRuntimes:
        - ruby3.3

  LambdikoDownloadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  RadikoDownloadFunction:
    Description: RadikoDownload Lambda Function ARN
    Value: !GetAtt RadikoDownloadFunction.Arn

  RadiruDownloadFunction:
    Description: RadiruDownload Lambda Function ARN
    Value: !GetAtt RadiruDownloadFunction.Arn

  ProgramSearchFunction:
    Description: ProgramSearch Lambda Function ARN
    Value: !GetAtt ProgramSearchFunction.Arn

  LambdikoDownloadBucket:
    Description: LambdikoDownload S3 Bucket ARN
    Value: !GetAtt LambdikoDownloadBucket.Arn
